# filelist.f
../src/grid.sv 
../src/riscv_grid_top.sv 
../src/riscv_scalable.sv 
../src/Log-XBar/parameters.v 
../src/Log-XBar/AddressDecoder_Req.sv 
../src/Log-XBar/ResponseTree.sv 
../src/Log-XBar/XBAR_TCDM.sv 
../src/Log-XBar/RequestBlock1CH.sv 
../src/Log-XBar/RequestBlock2CH.sv 
../src/Log-XBar/TestAndSet.sv 
../src/Log-XBar/FanInPrimitive_Resp.sv 
../src/Log-XBar/ResponseBlock.sv 
../src/Log-XBar/AddressDecoder_Resp.sv 
../src/Log-XBar/priority_Flag_Req.sv 
../src/Log-XBar/FanInPrimitive_Req.sv 
../src/Log-XBar/ArbitrationTree.sv 
../src/memories/dmem.sv 
../src/memories/imem.sv 
../src/memories/SRAM_32x4096_1rw.v
../src/riscv_core/opcode.vh 
../src/riscv_core/fetch_inst.sv 
../src/riscv_core/wb_selector.sv 
../src/riscv_core/read_reg.sv 
../src/riscv_core/data_in_gen.sv 
../src/riscv_core/branch_comp.sv 
../src/riscv_core/imm_generator.sv 
../src/riscv_core/gen_wr_mask.sv 
../src/riscv_core/cpu.sv 
../src/riscv_core/load_ex.sv 
../src/riscv_core/next_pc.sv 
../src/riscv_core/control_logic.sv 
../src/riscv_core/alu.sv 
../src/riscv_core/reg_file.sv 
